Created GH discussion link & Bug report config
pieces-app/obsidian-pieces pull request #20
Opened 2024-03-17 09:50 UTC by Sophyia7

I noticed there was no configuration for reporting bug so I created one and also added feature request for GH discussions.

2024-03-17 09:51 UTC, Sophyia7 commented
@mason-at-pieces do check this out

2024-03-17 19:18 UTC, mason-at-pieces commented
So when there is a new release for our obsidian plugin, the files in this repo are updated automatically.

@caleb-at-pieces do you know if a file added, would an update just remove the file or only update the existing files?

2024-03-18 15:35 UTC, caleb-at-pieces requested changes
I think we should be pushing people towards the support repo instead of letting them create bug reports on this repo.

So just like how we are sending them to discussions, we should probably send them to https://github.com/pieces-app/support/issues/new?template=bug.yml for the bug report

2024-03-18 15:36 UTC, caleb-at-pieces commented
> So when there is a new release for our obsidian plugin, the files in this repo are updated automatically.
> 
> @caleb-at-pieces do you know if a file added, would an update just remove the file or only update the existing files?

The CICD will not affect these templates

2024-03-18 16:00 UTC, mason-at-pieces commented
> I think we should be pushing people towards the support repo instead of letting them create bug reports on this repo.
> 
> So just like how we are sending them to discussions, we should probably send them to https://github.com/pieces-app/support/issues/new?template=bug.yml for the bug report

Yep I agree, @Sophyia7 can you remove the bug template and instead just add another link under the feature request one that goes to the issues page on our support repo?

2024-03-18 17:27 UTC, Sophyia7 commented
@mason-at-pieces updated it. Lmk what you think.

2024-03-18 17:50 UTC, caleb-at-pieces requested changes
some small copy adjustments and we are GTG

2024-03-18 17:50 UTC, caleb-at-pieces commented on .github/ISSUE_TEMPLATE/bug.yml
> +  - name: Submit Your Bug
'Report a Bug'

2024-03-18 17:50 UTC, caleb-at-pieces commented on .github/ISSUE_TEMPLATE/bug.yml
> +    about: Submit your bug or issues here for the Pieces team to resolve!
'Report a bug to the Pieces team.'

2024-03-18 17:50 UTC, caleb-at-pieces commented on .github/ISSUE_TEMPLATE/config.yml
> +  - name: Feature or Enhancement Request
'Request a Feature'

2024-03-18 17:50 UTC, caleb-at-pieces commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Post your idea for obsidian in discussions for the Pieces team and community to discuss!
'Post your idea for the Pieces Obsidian plugin in discussions for the Pieces team and community to discuss!'

2024-03-18 18:07 UTC, mason-at-pieces commented
Can we make sure we get these copy updates on all other repos as well @Sophyia7?

2024-04-01 14:29 UTC, closed without merging